### PR TITLE
paymentmethod parameter fix for lightbox

### PR DESCRIPTION
**Pull request by domi55**
currently datrans.js can only deal with the 'paymentmethod' parameter if its a string. so for multiple payment methods:

`paymentmethod="VIS,ECA"`

### CODE REVIEW

**Comment by domi55** [comment]
this breaks redirect mode support. sorry.

**Comment by maximkott** [comment]
@domi55 Hi Dominik.

I've built my own implementation for datatrans lightboxes. It fixes this issue, as well as some others and "should" be backwards compatible. I will push it as soon as it's tested. 

How did you find this repo anyway? :)

**Comment by domi55** [comment]
Ah! Even better! ;)
Its pretty cool! I tried to contact you yesterday. TWI should work on the test system btw.

**Comment by maximkott** [comment]
Thanks :) By phone? Sorry, must have missed that.

**Pull request closed without merging**
